%----------------------------------------------------------------
% Save parameters in .mat files to import into Dynare 
%----------------------------------------------------------------

% Economic parameters
save economicParameters.mat bbeta ppsi nnu bbBar eepsilon ttau vvarthetaB vvarthetaT...
    vzGrid vzInvariant mzTransition A_SS w_SS r_RepSS N_RepSS vShareGrid vShareFraction...
    rrhoTFP ssigmaTFP rrhoMP ssigmaMP ttheta pphi

% Approximation parameters
save approximationParameters.mat nz nAssets nState nAssetsFine nStateFine...
    nAssetsQuadrature nStateQuadrature nMeasure nMeasureCoefficients nShare...
    assetsMin assetsMax...
    tolerance_SS_root tolerance_SS_invhist maxIterations tolerance dampening numNewton

% Grids
save grids.mat vAssetsGridZeros vAssetsGrid mzGrid mAssetsGrid mzPrimeGrid vAssetsGridFine ...
    vAssetsGridFineZeros mzGridFine mAssetsGridFine mzPrimeGridFine vQuadratureWeights ...
    vAssetsGridQuadratureZeros vAssetsGridQuadrature mzGridQuadrature mAssetsGridQuadrature

% Polynomials
save polynomials.mat vAssetsPoly vAssetsPolySquared vAssetsPolyFine vAssetsPolyQuadrature vAssetsPolyBC